/**
 * Simulates a full season and prints the engine's per-team-per-game statistical
 * profile against empirically derived league targets, with deltas and derived
 * tolerance bands — the calibration acceptance test for the engine.
 *
 * It drives simulateGame directly over the same schedule + per-game seed
 * sequence simulateSeason uses, so the box-score aggregates are identical, but
 * it additionally reads the play-by-play stream for per-zone FG%, the
 * six-zone/three-bucket shot mix, the terminal play-type distribution, the
 * assisted-shot rate by zone, and the per-game scoring margin — none of which
 * survive into SeasonResult.
 *
 * Pass/fail contract (Stage 1): every ENFORCED stat must land within its
 * tolerance band around the empirical target. Targets and bands are derived
 * from data/nba/normalized/ by `npx tsx scripts/derive-league-targets.ts` and
 * hand-transcribed here with provenance; see docs/LEAGUE_TARGETS.md for the
 * full derivation (sources, formulas, sample sizes, per-season values).
 * DO NOT hand-edit target numbers — re-run the derivation and re-transcribe.
 * INFORMATIONAL stats are logged with their real-league reference but never
 * fail the profile; each is annotated with the stage that owns closing its
 * gap. Tier assignment is fixed per-task before tuning, never outcome-based.
 */
import { Player } from '../src/models/player';
import { Team } from '../src/models/team';
import { PlayType, ShotZone } from '../src/models/game';
import { SeededRNG } from '../src/lib/rng';
import { simulateGame } from '../src/engine';
import { generateSchedule } from '../src/engine/schedule';
import { selectLatestCareerStats } from '../src/ratings/derivation';
import { loadLeaguePool } from './league-pool';

// ---------------------------------------------------------------------------
// ENFORCED targets — derived from real NBA data, 2023-24..2025-26 pooled
// (3,690 games / 7,380 team-games; 657,387 shot attempts). Source:
// docs/LEAGUE_TARGETS.md (generated by scripts/derive-league-targets.ts).
// tol = max(max single-season deviation from the pooled value, documented
// floor); "(floor)"/"(season-dev)" notes which term bound each band.
// ---------------------------------------------------------------------------
const TARGETS: Record<string, { v: number; tol: number }> = {
  // League box profile, per team-game.
  pace: { v: 101.98, tol: 1.0 }, // poss = FGA + 0.44·FTA + TOV − ORB (floor)
  pts: { v: 114.55, tol: 1.5 }, // games contract (floor)
  ppp: { v: 1.1232, tol: 0.015 }, // pts/poss (floor)
  fga: { v: 89.08, tol: 1.0 }, // shot_events (floor)
  fgPct: { v: 0.4709, tol: 0.005 }, // shot_events (floor)
  tpa: { v: 36.56, tol: 1.45 }, // shot_events (season-dev; 3PA is trending up)
  tpPct: { v: 0.3618, tol: 0.008 }, // shot_events (floor)
  fta: { v: 22.29, tol: 1.19 }, // pbp free-throw rows (season-dev)
  ftPct: { v: 0.7823, tol: 0.01 }, // pbp free-throw rows (floor)
  orb: { v: 11.04, tol: 0.5 }, // box_advanced player sums (floor)
  drb: { v: 32.81, tol: 0.8 }, // box_advanced player sums (floor)
  reb: { v: 43.8, tol: 1.0 }, // box_advanced player sums (floor)
  ast: { v: 26.66, tol: 0.8 }, // box_advanced player sums (floor)
  stl: { v: 8.04, tol: 0.57 }, // box_advanced player sums (season-dev)
  blk: { v: 4.97, tol: 0.5 }, // box_advanced player sums (floor)
  tov: { v: 14.14, tol: 0.53 }, // pbp turnover rows incl. team TOs (season-dev)
  margin: { v: 12.87, tol: 1.0 }, // mean abs final margin, games contract (floor)
  // Realized FG% per engine zone (post-heave; settled six-zone mapping —
  // see the mapping block above BASE_FG_PCT_BY_ZONE in engine/constants.ts).
  'zoneFgPct.rim': { v: 0.6659, tol: 0.008 }, // n=188,112 FGA (floor)
  'zoneFgPct.short_midrange': { v: 0.4412, tol: 0.01 }, // n=151,521 FGA (floor)
  'zoneFgPct.long_midrange': { v: 0.4135, tol: 0.012 }, // n=47,966 FGA (floor)
  'zoneFgPct.corner_three': { v: 0.3881, tol: 0.012 }, // n=69,306 FGA (floor)
  'zoneFgPct.above_break_three': { v: 0.3603, tol: 0.008 }, // n=152,549 FGA (floor)
  'zoneFgPct.deep_three': { v: 0.3379, tol: 0.015 }, // n=46,212 FGA; smallest zone (floor)
  // Six-zone shot mix (share of non-heave FGA).
  'zoneShare.rim': { v: 0.2869, tol: 0.012 }, // (floor)
  'zoneShare.short_midrange': { v: 0.2311, tol: 0.012 }, // (floor)
  'zoneShare.long_midrange': { v: 0.0732, tol: 0.012 }, // (floor)
  'zoneShare.corner_three': { v: 0.1057, tol: 0.012 }, // (floor)
  'zoneShare.above_break_three': { v: 0.2327, tol: 0.012 }, // (floor)
  'zoneShare.deep_three': { v: 0.0705, tol: 0.012 }, // (floor)
  // Three-bucket mix (sums of the six-zone counts; mid includes paint-non-RA).
  'bucketShare.rim': { v: 0.2869, tol: 0.015 }, // (floor)
  'bucketShare.mid': { v: 0.3043, tol: 0.015 }, // (floor)
  'bucketShare.three': { v: 0.4088, tol: 0.0159 }, // (season-dev)
};

// ---------------------------------------------------------------------------
// INFORMATIONAL references — logged, never pass/fail. Same derivation and
// provenance as above (docs/LEAGUE_TARGETS.md); each family is annotated with
// the stage that owns closing its gap.
// ---------------------------------------------------------------------------

// Synergy offensive play-type shares, Misc excluded and renormalized,
// PRBallHandler+PRRollMan combined. Owner: Stage 2 (selection lives hardcoded
// in src/engine/play-types.ts — out of Stage 1 scope). The engine side is
// measured from TERMINAL emitted event types (the chain can replace the
// initial play type) with `putback` excluded and renormalized, since Synergy's
// putback category (OffRebound) is not harvested.
const INFO_PLAY_TYPE: Record<Exclude<PlayType, 'putback'>, number> = {
  isolation: 0.0819,
  pick_and_roll: 0.254,
  post_up: 0.0424,
  spot_up: 0.2561,
  transition: 0.1966,
  cut: 0.0732,
  off_screen: 0.0408,
  handoff: 0.055,
};

// Assisted share of made FGs by zone (NBA scorekeeper attribution). Owner:
// Stage 2/3 — the NBA assist definition (credited through a dribble or two
// after the catch) is materially more liberal than the engine's strict
// pass-into-the-make chain, so levels are expected to differ; the sign
// structure (corner three highest by a wide margin) is the sanity check.
const INFO_ASSISTED_RATE: Record<ShotZone, number> = {
  rim: 0.5816,
  short_midrange: 0.4839,
  long_midrange: 0.4615,
  corner_three: 0.9667,
  above_break_three: 0.8077,
  deep_three: 0.7616,
};
const INFO_ASSISTED_RATE_OVERALL = 0.6355;

// PBP-derived reference rates. Owners: and-one/putback/ORB-rate Stage 3;
// the transition FGA share is a timing-proxy cross-check for Synergy's
// transition frequency (owner: Stage 2) and is not directly engine-comparable.
const INFO_PBP = {
  transitionFgaShare: 0.1886,
  andOneRate: 0.0561,
  putbackFgaShare: 0.0196,
  orbRate: 0.2518,
};

const SIX_ZONES: ShotZone[] = [
  'rim',
  'short_midrange',
  'long_midrange',
  'corner_three',
  'above_break_three',
  'deep_three',
];

function zoneBucket(z: ShotZone): 'rim' | 'mid' | 'three' {
  if (z === 'rim') return 'rim';
  if (z === 'short_midrange' || z === 'long_midrange') return 'mid';
  return 'three';
}

interface PlayerProfileTotals {
  teamId: string;
  games: number;
  minutes: number;
  points: number;
  fga: number;
  ftm: number;
  fta: number;
}

function rank(values: number[]): number[] {
  const indexed = values.map((value, index) => ({ value, index }));
  indexed.sort((a, b) => a.value - b.value || a.index - b.index);
  const ranks = new Array<number>(values.length);
  for (let start = 0; start < indexed.length;) {
    let end = start + 1;
    while (end < indexed.length && indexed[end].value === indexed[start].value) end++;
    const averageRank = (start + 1 + end) / 2;
    for (let i = start; i < end; i++) ranks[indexed[i].index] = averageRank;
    start = end;
  }
  return ranks;
}

function pearson(xs: number[], ys: number[]): number {
  if (xs.length !== ys.length || xs.length < 2) return Number.NaN;
  const meanX = xs.reduce((sum, value) => sum + value, 0) / xs.length;
  const meanY = ys.reduce((sum, value) => sum + value, 0) / ys.length;
  let covariance = 0, varianceX = 0, varianceY = 0;
  for (let i = 0; i < xs.length; i++) {
    const dx = xs[i] - meanX;
    const dy = ys[i] - meanY;
    covariance += dx * dy;
    varianceX += dx * dx;
    varianceY += dy * dy;
  }
  const denominator = Math.sqrt(varianceX * varianceY);
  return denominator === 0 ? Number.NaN : covariance / denominator;
}

function spearman(xs: number[], ys: number[]): number {
  return pearson(rank(xs), rank(ys));
}

async function main() {
  const pool = await loadLeaguePool(process.argv.slice(2));
  const { teams, players } = pool;
  if (pool.alternate) console.log(`INFORMATIONAL — alternate pool (${pool.directory}); no gate; S2d owns the gated run`);

  // Mirror simulateSeason's RNG/seed sequence so aggregates match `npm run
  // profile`-via-season exactly, while also exposing PBP-derived stats.
  const rng = new SeededRNG(2026);
  const teamById = new Map(teams.map((t) => [t.id, t]));
  const playersByTeam = new Map<string, Player[]>();
  for (const t of teams) playersByTeam.set(t.id, []);
  for (const p of players) {
    if (p.teamId && playersByTeam.has(p.teamId)) playersByTeam.get(p.teamId)!.push(p);
  }
  const schedule = generateSchedule(teams, rng);

  let pts = 0, fgm = 0, fga = 0, tpm = 0, tpa = 0, ftm = 0, fta = 0;
  let orb = 0, drb = 0, reb = 0, ast = 0, stl = 0, blk = 0, tov = 0;
  let marginSum = 0;
  let gamesPlayed = 0;
  const playerTotals = new Map<string, PlayerProfileTotals>();

  // Event-stream measurements ("stats derive from the stream" applies to
  // calibration measurement too).
  const zoneAtt = new Map<ShotZone, number>(SIX_ZONES.map((z) => [z, 0]));
  const zoneMade = new Map<ShotZone, number>(SIX_ZONES.map((z) => [z, 0]));
  const zoneAssisted = new Map<ShotZone, number>(SIX_ZONES.map((z) => [z, 0]));
  const playTypeCounts = new Map<PlayType, number>();
  let andOnes = 0;

  for (const sg of schedule) {
    const home = teamById.get(sg.homeTeamId);
    const away = teamById.get(sg.awayTeamId);
    if (!home || !away) continue;
    const homePlayers = playersByTeam.get(home.id) ?? [];
    const awayPlayers = playersByTeam.get(away.id) ?? [];
    if (homePlayers.length < 5 || awayPlayers.length < 5) continue;

    const gameSeed = rng.nextInt(1, 2_000_000_000);
    const sim = simulateGame(home, away, homePlayers, awayPlayers, sg.id, 'profile', `day-${sg.day}`, gameSeed);
    gamesPlayed++;

    for (const side of [sim.boxScore.homeTeam, sim.boxScore.awayTeam]) {
      const t = side.totals;
      pts += t.points; fgm += t.fieldGoalsMade; fga += t.fieldGoalsAttempted;
      tpm += t.threePointersMade; tpa += t.threePointersAttempted;
      ftm += t.freeThrowsMade; fta += t.freeThrowsAttempted;
      orb += t.offensiveRebounds; drb += t.defensiveRebounds; reb += t.rebounds;
      ast += t.assists; stl += t.steals; blk += t.blocks; tov += t.turnovers;

      for (const line of side.players) {
        const total = playerTotals.get(line.playerId) ?? {
          teamId: side.teamId,
          games: 0,
          minutes: 0,
          points: 0,
          fga: 0,
          ftm: 0,
          fta: 0,
        };
        total.games++;
        total.minutes += line.minutes;
        total.points += line.stats.points;
        total.fga += line.stats.fieldGoalsAttempted;
        total.ftm += line.stats.freeThrowsMade;
        total.fta += line.stats.freeThrowsAttempted;
        playerTotals.set(line.playerId, total);
      }
    }

    for (const e of sim.playByPlay) {
      // Terminal play-type distribution over possession-ending outcomes
      // (approximates Synergy's possession universe; non-shooting fouls and
      // end-of-period events excluded).
      if (e.outcome === 'made_shot' || e.outcome === 'missed_shot' || e.outcome === 'and_one' || e.outcome === 'turnover') {
        playTypeCounts.set(e.type, (playTypeCounts.get(e.type) ?? 0) + 1);
      }
      if (!e.shotZone) continue;
      if (e.outcome !== 'made_shot' && e.outcome !== 'and_one' && e.outcome !== 'missed_shot') continue;
      zoneAtt.set(e.shotZone, (zoneAtt.get(e.shotZone) ?? 0) + 1);
      const made = e.outcome !== 'missed_shot';
      if (made) {
        zoneMade.set(e.shotZone, (zoneMade.get(e.shotZone) ?? 0) + 1);
        if (e.assistPlayerId) zoneAssisted.set(e.shotZone, (zoneAssisted.get(e.shotZone) ?? 0) + 1);
        if (e.outcome === 'and_one') andOnes++;
      }
    }

    marginSum += Math.abs(sim.result.homeScore - sim.result.awayScore);
  }

  const tg = gamesPlayed * 2; // team-games
  const per = (x: number) => x / tg;
  const possessions = per(fga) + 0.44 * per(fta) + per(tov) - per(orb);

  const eng: Record<string, number> = {
    pace: possessions, pts: per(pts), fgPct: fgm / fga, ppp: per(pts) / possessions,
    fga: per(fga), tpa: per(tpa), tpPct: tpm / tpa, fta: per(fta), ftPct: ftm / fta,
    orb: per(orb), drb: per(drb), reb: per(reb), ast: per(ast),
    stl: per(stl), blk: per(blk), tov: per(tov),
    margin: marginSum / gamesPlayed,
  };

  const totalZoneAtt = SIX_ZONES.reduce((acc, z) => acc + zoneAtt.get(z)!, 0);
  const bucketAtt = { rim: 0, mid: 0, three: 0 };
  for (const z of SIX_ZONES) {
    eng[`zoneFgPct.${z}`] = zoneMade.get(z)! / zoneAtt.get(z)!;
    eng[`zoneShare.${z}`] = zoneAtt.get(z)! / totalZoneAtt;
    bucketAtt[zoneBucket(z)] += zoneAtt.get(z)!;
  }
  eng['bucketShare.rim'] = bucketAtt.rim / totalZoneAtt;
  eng['bucketShare.mid'] = bucketAtt.mid / totalZoneAtt;
  eng['bucketShare.three'] = bucketAtt.three / totalZoneAtt;

  // --- output helpers -------------------------------------------------------
  const pctLike = (key: string) =>
    key.endsWith('Pct') || key.startsWith('zoneFgPct.') || key.startsWith('zoneShare.') ||
    key.startsWith('bucketShare.') || key.startsWith('assisted.') || key.startsWith('playType.');
  const fmt = (key: string, v: number) =>
    key === 'ppp' ? v.toFixed(3) : pctLike(key) ? (v * 100).toFixed(1) : v.toFixed(1);

  let fails = 0;
  let enforcedCount = 0;
  const printEnforced = (label: string, key: string) => {
    const e = eng[key];
    const { v: target, tol } = TARGETS[key];
    const delta = e - target;
    const within = Math.abs(delta) <= tol;
    enforcedCount++;
    if (!within) fails++;
    const d = key === 'ppp' ? delta.toFixed(3) : pctLike(key) ? (delta * 100).toFixed(1) : delta.toFixed(1);
    const tolStr = key === 'ppp' ? tol.toFixed(3) : pctLike(key) ? (tol * 100).toFixed(1) : tol.toFixed(1);
    console.log(
      label.padEnd(22) +
      fmt(key, e).padStart(8) +
      fmt(key, target).padStart(8) +
      (delta >= 0 ? '+' + d : d).padStart(8) +
      ('±' + tolStr).padStart(8) +
      '  ' + (within ? 'OK' : '⚠️ OUT')
    );
  };
  const header = () =>
    console.log('Stat'.padEnd(22) + 'Engine'.padStart(8) + 'Target'.padStart(8) + 'Δ'.padStart(8) + 'Tol'.padStart(8) + '  Flag');

  console.log(`Engine profile (${gamesPlayed} games, seed 2026). Pass/fail vs derived NBA targets`);
  console.log('(2023-24..2025-26 pooled — docs/LEAGUE_TARGETS.md).\n');

  console.log('ENFORCED — league box profile (per team-game)');
  console.log('-'.repeat(64));
  header();
  const boxRows: [string, string][] = [
    ['Pace (poss)', 'pace'], ['Points', 'pts'], ['PPP', 'ppp'],
    ['FGA', 'fga'], ['FG%', 'fgPct'], ['3PA', 'tpa'], ['3P%', 'tpPct'],
    ['FTA', 'fta'], ['FT%', 'ftPct'], ['OREB', 'orb'], ['DREB', 'drb'],
    ['REB', 'reb'], ['AST', 'ast'], ['STL', 'stl'], ['BLK', 'blk'], ['TOV', 'tov'],
    ['Avg margin', 'margin'],
  ];
  for (const [label, key] of boxRows) printEnforced(label, key);

  console.log('\nENFORCED — shooting profile (zone FG% / shot mix, % of FGA)');
  console.log('-'.repeat(64));
  header();
  for (const z of SIX_ZONES) printEnforced(`FG% ${z}`, `zoneFgPct.${z}`);
  for (const z of SIX_ZONES) printEnforced(`share ${z}`, `zoneShare.${z}`);
  for (const b of ['rim', 'mid', 'three'] as const) printEnforced(`share bucket:${b}`, `bucketShare.${b}`);

  console.log('-'.repeat(64));
  console.log(pool.alternate ? 'INFORMATIONAL — alternate pool; band outcomes do not gate S2c1.' : fails === 0
    ? `PASS (${enforcedCount} of ${enforcedCount} enforced stats within tolerance)`
    : `FAIL (${fails} of ${enforcedCount} enforced stats out of tolerance)`);

  // --- informational (logged, never pass/fail) ------------------------------
  console.log('\nINFORMATIONAL (no pass/fail; owner = stage that closes the gap)');
  console.log('-'.repeat(72));

  const terminalPoss = [...playTypeCounts.values()].reduce((a, b) => a + b, 0);
  const putbackCount = playTypeCounts.get('putback') ?? 0;
  const nonPutback = terminalPoss - putbackCount;
  console.log('Play-type distribution, terminal emitted events vs Synergy [Stage 2]');
  console.log('(engine putback share ' + ((putbackCount / terminalPoss) * 100).toFixed(1) +
    '% excluded+renormalized; Synergy lacks a harvested putback category)');
  console.log('Type'.padEnd(22) + 'Engine'.padStart(8) + 'Real'.padStart(8) + 'Δ'.padStart(8));
  for (const pt of Object.keys(INFO_PLAY_TYPE) as (keyof typeof INFO_PLAY_TYPE)[]) {
    const engShare = (playTypeCounts.get(pt) ?? 0) / nonPutback;
    const real = INFO_PLAY_TYPE[pt];
    console.log(
      pt.padEnd(22) +
      (engShare * 100).toFixed(1).padStart(8) +
      (real * 100).toFixed(1).padStart(8) +
      (((engShare - real) >= 0 ? '+' : '') + ((engShare - real) * 100).toFixed(1)).padStart(8)
    );
  }

  console.log('\nAssisted share of made FGs by zone, chain assists vs NBA scorekeeper [Stage 2/3]');
  console.log('(NBA attribution is more liberal than the chain — levels differ by design;');
  console.log(' corner three should be the highest zone by a wide margin in both)');
  console.log('Zone'.padEnd(22) + 'Engine'.padStart(8) + 'Real'.padStart(8) + 'Δ'.padStart(8));
  let madeAll = 0, assistedAll = 0;
  for (const z of SIX_ZONES) {
    const made = zoneMade.get(z)!;
    const assisted = zoneAssisted.get(z)!;
    madeAll += made; assistedAll += assisted;
    const engRate = assisted / made;
    const real = INFO_ASSISTED_RATE[z];
    console.log(
      z.padEnd(22) +
      (engRate * 100).toFixed(1).padStart(8) +
      (real * 100).toFixed(1).padStart(8) +
      (((engRate - real) >= 0 ? '+' : '') + ((engRate - real) * 100).toFixed(1)).padStart(8)
    );
  }
  console.log(
    'overall'.padEnd(22) +
    ((assistedAll / madeAll) * 100).toFixed(1).padStart(8) +
    (INFO_ASSISTED_RATE_OVERALL * 100).toFixed(1).padStart(8) +
    ((((assistedAll / madeAll) - INFO_ASSISTED_RATE_OVERALL) >= 0 ? '+' : '') +
      (((assistedAll / madeAll) - INFO_ASSISTED_RATE_OVERALL) * 100).toFixed(1)).padStart(8)
  );

  const engAndOneRate = andOnes / madeAll;
  const engOrbRate = orb / (orb + drb);
  console.log('\nOther PBP-derived references');
  console.log(`And-one rate (per made FG):   engine ${(engAndOneRate * 100).toFixed(1)}%  real ${(INFO_PBP.andOneRate * 100).toFixed(1)}%  [Stage 3]`);
  console.log(`Putback share of possessions: engine ${((putbackCount / terminalPoss) * 100).toFixed(1)}%  real ~${(INFO_PBP.putbackFgaShare * 100).toFixed(1)}% of FGA  [Stage 3]`);
  console.log(`ORB rate ORB/(ORB+DRB):       engine ${(engOrbRate * 100).toFixed(1)}%  real ${(INFO_PBP.orbRate * 100).toFixed(1)}%  [Stage 3]`);
  console.log(`Real transition FGA timing proxy: ${(INFO_PBP.transitionFgaShare * 100).toFixed(1)}% of FGA — cross-check for Synergy transition, not engine-comparable  [Stage 2]`);
  console.log('Turnover-type mix: real subtype mix in docs/LEAGUE_TARGETS.md (NBA subtypes do not map 1:1 onto engine TurnoverType)  [Stage 3]');

  // --- player-level distribution (unchanged) --------------------------------
  const playerById = new Map(players.map((player) => [player.id, player]));
  const usageQualified = [...playerTotals.entries()].filter(([, total]) => total.minutes >= 500);
  const usageSpearman = spearman(
    usageQualified.map(([playerId]) => playerById.get(playerId)!.tendencies.usageRate),
    usageQualified.map(([, total]) => total.fga / total.minutes),
  );

  const scoringQualified = [...playerTotals.entries()].flatMap(([playerId, total]) => {
    const raw = selectLatestCareerStats(playerById.get(playerId)?.careerStats ?? []);
    if (!raw || raw.minutesPerGame < 15 || total.minutes < 500 || total.games === 0) return [];
    return [{ simPpg: total.points / total.games, realPpg: raw.stats.points }];
  });
  const scoringPearson = pearson(
    scoringQualified.map((row) => row.simPpg),
    scoringQualified.map((row) => row.realPpg),
  );

  const teamPointTotals = new Map<string, number>();
  const teamLeaderPoints = new Map<string, number>();
  for (const total of playerTotals.values()) {
    teamPointTotals.set(total.teamId, (teamPointTotals.get(total.teamId) ?? 0) + total.points);
    teamLeaderPoints.set(total.teamId, Math.max(teamLeaderPoints.get(total.teamId) ?? 0, total.points));
  }
  const topScorerShares = [...teamPointTotals].map(([teamId, total]) =>
    total === 0 ? 0 : (teamLeaderPoints.get(teamId) ?? 0) / total);
  const topScorerShare = topScorerShares.reduce((sum, value) => sum + value, 0) / topScorerShares.length;

  const ftQualified = [...playerTotals.entries()].flatMap(([playerId, total]) => {
    const raw = selectLatestCareerStats(playerById.get(playerId)?.careerStats ?? []);
    if (!raw || raw.stats.freeThrowsAttempted < 2 || total.fta === 0) return [];
    return [{ total, raw }];
  });
  const simFtm = ftQualified.reduce((sum, row) => sum + row.total.ftm, 0);
  const simFta = ftQualified.reduce((sum, row) => sum + row.total.fta, 0);
  const realFtm = ftQualified.reduce(
    (sum, row) => sum + row.raw.stats.freeThrowPct * row.raw.stats.freeThrowsAttempted,
    0,
  );
  const realFta = ftQualified.reduce((sum, row) => sum + row.raw.stats.freeThrowsAttempted, 0);
  const simFtPcts = ftQualified.map((row) => row.total.ftm / row.total.fta);
  const usages = players.map((player) => player.tendencies.usageRate);
  const usageFloorCount = usages.filter((value) => value === 0.10).length;

  console.log('\nPlayer-level distribution');
  console.log('-'.repeat(72));
  console.log(`Usage rate roster min/mean/max: ${Math.min(...usages).toFixed(3)} / ${(usages.reduce((a, b) => a + b, 0) / usages.length).toFixed(3)} / ${Math.max(...usages).toFixed(3)} (${usageFloorCount} at 0.10 floor)`);
  console.log(`Usage vs sim FGA/min Spearman: ${usageSpearman.toFixed(3)} (n=${usageQualified.length}, min 500 sim minutes)`);
  console.log(`Sim PPG vs real PPG Pearson:   ${scoringPearson.toFixed(3)} (n=${scoringQualified.length}, real MPG >= 15, sim minutes >= 500)`);
  console.log(`Team top-scorer points share:  ${(topScorerShare * 100).toFixed(1)}% (real reference 19-22%)`);
  console.log(`Qualified FT% sim vs real:     ${(simFtm / simFta * 100).toFixed(1)}% vs ${(realFtm / realFta * 100).toFixed(1)}% (n=${ftQualified.length}, real FTA >= 2)`);
  console.log(`Qualified sim FT% min/max:     ${(Math.min(...simFtPcts) * 100).toFixed(1)}% / ${(Math.max(...simFtPcts) * 100).toFixed(1)}%`);

  process.exitCode = fails > 0 && !pool.alternate ? 1 : 0;
}

main().catch((e) => { console.error(e); process.exit(1); });
