/** Deterministic S2c2 candidate measurement report. Regenerate; never hand-edit.
 * Runs four full deterministic seasons (candidate profile under real diets,
 * candidate assisted-zone diagnosis under real diets, the S2c2-R modifier
 * decomposition, and the default active-pool profile), so generation and
 * `--check` take several minutes each. */
import { execFileSync } from 'child_process';
import { createHash } from 'crypto';
import { readFileSync, writeFileSync } from 'fs';
import path from 'path';

const OUT = path.join(process.cwd(), 'docs/S2C2_ASSIST_AND_DIET_REPORT.md');
const CANONICAL_PRE_S2C2_PROFILE = '7482a68d7859ff8c8f962832ff4978ba32621c700594fd4deae785e82759e95a';
const CANONICAL_CALIBRATE = 'a9f79617711614e8199ee43e48f3f74e4ef16fb6fc9379f3a62f6c41a14b90e4';
// Must stay in sync with the appendix-strip pattern in scripts/test-s2c1-r.ts.
const S2C2_APPENDIX_RE = /\nScorekeeper-aligned assisted proxy by zone \[S2c2; INFORMATIONAL\][\s\S]*?Proxy corner-three highest: (?:true|false)\n/;

const args = process.argv.slice(2);
const check = args.includes('--check');
const base = args.find((arg) => arg.startsWith('--base-commit='))?.slice(14);
if (!base || !/^[0-9a-f]{7,64}$/i.test(base)) throw new Error('Usage: --base-commit=<immutable SHA> [--check]');
if (args.some((arg) => arg !== '--check' && !arg.startsWith('--base-commit='))) throw new Error('Unknown argument');

function run(script: string, scriptArgs: string[] = []): string {
  return execFileSync(process.execPath, ['--import', 'tsx', script, ...scriptArgs], { cwd: process.cwd(), encoding: 'utf8' });
}
function slice(text: string, start: string, end: string): string {
  const from = text.indexOf(start); const to = text.indexOf(end, from);
  if (from < 0 || to < 0) throw new Error(`Could not extract report section: ${start}`);
  return text.slice(from, to).trim();
}
const candidate = run('scripts/profile-engine.ts', ['--league-dir', 'data/league-candidate', '--shot-zones=real', '--seed=2026']);
const diagnosis = run('scripts/diagnose-assists.ts', ['--league-dir=data/league-candidate', '--shot-zones=real', '--seed=2026']);
const decomposition = run('scripts/diagnose-s2c2-zones.ts', ['--league-dir=data/league-candidate', '--shot-zones=real', '--seed=2026']);
const defaultProfile = run('scripts/profile-engine.ts');
const hash = (text: string) => createHash('sha256').update(text).digest('hex');

// Mechanical per-row |Δ| ≤ 2·tol predicate over every printed share row (six
// zones + three buckets), computed from the same printed Engine/Target/Δ/Tol
// values the shot-mix block carries.
const shotMix = slice(candidate, 'ENFORCED — shooting profile', 'INFORMATIONAL — alternate pool');
const shareRows = shotMix.split('\n')
  .map((line) => line.match(/^(share \S+)\s+(-?[\d.]+)\s+(-?[\d.]+)\s+([+-][\d.]+)\s+±([\d.]+)/))
  .filter((m): m is RegExpMatchArray => m !== null)
  .map((m) => ({ row: m[1], delta: Number(m[4]), twoTol: 2 * Number(m[5]) }));
if (shareRows.length !== 9) throw new Error(`Expected 9 share rows in the shot-mix block, found ${shareRows.length}`);
const predicateTable = [
  '| Row | Δ (pp) | 2·tol (pp) | \\|Δ\\| ≤ 2·tol |',
  '| --- | --- | --- | --- |',
  ...shareRows.map((r) => `| ${r.row} | ${r.delta >= 0 ? '+' : ''}${r.delta.toFixed(1)} | ${r.twoTol.toFixed(1)} | ${Math.abs(r.delta) <= r.twoTol} |`),
].join('\n');
const anyShareFail = shareRows.some((r) => Math.abs(r.delta) > r.twoTol);

// Permitted-diff record: the S2c2 appendix is the only sanctioned change to
// default profile output; stripped of it, the output must equal the pre-S2c2
// canonical capture.
const appendixMatch = defaultProfile.match(S2C2_APPENDIX_RE);
if (!appendixMatch) throw new Error('Could not locate the S2c2 appendix in default profile output');
const strippedDefault = defaultProfile.replace(S2C2_APPENDIX_RE, '');

const report = `# S2c2 assist and diet report

> Generated by \`node --import tsx scripts/report-s2c2.ts --base-commit=${base}\`. Regenerate; never hand-edit.
> \`--check\` byte-compares this file against a fresh deterministic measurement run.

## Provenance

- Implementation base: \`${base}\`
- Candidate input: \`data/league-candidate\`; selector: candidate; shot-zone table: real (all three candidate runs)
- Seed: **2026**
- Runs: \`profile-engine.ts --league-dir data/league-candidate --shot-zones=real --seed=2026\`;
  \`diagnose-assists.ts --league-dir=data/league-candidate --shot-zones=real --seed=2026\`;
  \`diagnose-s2c2-zones.ts --league-dir=data/league-candidate --shot-zones=real --seed=2026\`;
  \`profile-engine.ts\` (default active pool)
- Decision record: [S2C2_ASSIST_DECISION.md](S2C2_ASSIST_DECISION.md)
- Default profile SHA-256 after S2c2 appendix: \`${hash(defaultProfile)}\`
- Canonical pre-S2c2 profile SHA-256: \`${CANONICAL_PRE_S2C2_PROFILE}\`
- Default profile stripped of the S2c2 appendix equals the pre-S2c2 canonical capture: **${hash(strippedDefault) === CANONICAL_PRE_S2C2_PROFILE}**
- Canonical calibrate SHA-256: \`${CANONICAL_CALIBRATE}\`

## Candidate real-diet shot mix

\`\`\`text
${shotMix}
\`\`\`

### Zone-share \`|Δ| ≤ 2·tol\` predicate (mechanical)

${predicateTable}

## Downstream shot-zone modifier decomposition

${anyShareFail
    ? 'Included because at least one share-row predicate above is false. Measurements only; attribution and outcome routing live in `docs/ROADMAP.md` §4.2.'
    : 'All share-row predicates above are true; the decomposition is retained as reference measurements.'}

\`\`\`text
${decomposition.trim()}
\`\`\`

## Candidate emitted play types and assisted rates

\`\`\`text
${slice(candidate, 'Play-type distribution', 'Other PBP-derived references')}
\`\`\`

## Pass and catch-and-shoot provenance (per zone)

\`\`\`text
${slice(diagnosis, '=== Assisted-zone diagnosis', 'Terminal play-type split')}
\`\`\`

## Locked diet restoration

| Play type | Legacy shaded | Candidate real |
| --- | --- | --- |
| cut | rim .650; short mid .350 | rim .800; short mid .200 |
| spot_up | rim .070; short .090; long .050; corner .340; above .350; deep .100 | rim .130; short .084; long .050; corner .317; above .326; deep .093 |

Spot-up redistribution: each shaded donor weight × \`(.880 − .060) / .880\`, rounded to three decimals. Cut and spot-up rim values are documented-range midpoints.

## Default-profile permitted diff (the exact added lines)

The only sanctioned S2c2 change to default \`npm run profile --silent\` output is this appended informational block (the strip pattern is shared with \`scripts/test-s2c1-r.ts\`):

\`\`\`text
${appendixMatch[0].trim()}
\`\`\`
`;

if (check) {
  if (readFileSync(OUT, 'utf8') !== report) throw new Error('--check FAILED: S2c2 report differs');
  console.log('--check OK: docs/S2C2_ASSIST_AND_DIET_REPORT.md byte-identical.');
} else {
  writeFileSync(OUT, report);
  console.log(`Wrote ${OUT}`);
}
