/** Deterministic S2c2 candidate measurement report. Regenerate; never hand-edit. */
import { execFileSync } from 'child_process';
import { createHash } from 'crypto';
import { readFileSync, writeFileSync } from 'fs';
import path from 'path';

const OUT = path.join(process.cwd(), 'docs/S2C2_ASSIST_AND_DIET_REPORT.md');
const args = process.argv.slice(2);
const check = args.includes('--check');
const base = args.find((arg) => arg.startsWith('--base-commit='))?.slice(14);
if (!base || !/^[0-9a-f]{7,64}$/i.test(base)) throw new Error('Usage: --base-commit=<immutable SHA> [--check]');
if (args.some((arg) => arg !== '--check' && !arg.startsWith('--base-commit='))) throw new Error('Unknown argument');

function run(script: string, scriptArgs: string[] = []): string {
  return execFileSync(process.execPath, ['--import', 'tsx', script, ...scriptArgs], { cwd: process.cwd(), encoding: 'utf8' });
}
function slice(text: string, start: string, end: string): string {
  const from = text.indexOf(start); const to = text.indexOf(end, from);
  if (from < 0 || to < 0) throw new Error(`Could not extract report section: ${start}`);
  return text.slice(from, to).trim();
}
const candidate = run('scripts/profile-engine.ts', ['--league-dir', 'data/league-candidate', '--shot-zones=real', '--seed=2026']);
const diagnosis = run('scripts/diagnose-assists.ts', ['--league-dir=data/league-candidate', '--seed=2026']);
const defaultProfile = run('scripts/profile-engine.ts');
const hash = (text: string) => createHash('sha256').update(text).digest('hex');
const report = `# S2c2 assist and diet report

> Generated by \`node --import tsx scripts/report-s2c2.ts --base-commit=${base}\`. Regenerate; never hand-edit.
> \`--check\` byte-compares this file against a fresh deterministic measurement run.

## Provenance

- Implementation base: \`${base}\`
- Candidate input: \`data/league-candidate\`; selector: candidate; shot-zone table: real
- Seed: **2026**
- Decision record: [S2C2_ASSIST_DECISION.md](S2C2_ASSIST_DECISION.md)
- Default profile SHA-256 after S2c2 appendix: \`${hash(defaultProfile)}\`
- Canonical pre-S2c2 profile SHA-256: \`7482a68d7859ff8c8f962832ff4978ba32621c700594fd4deae785e82759e95a\`
- Canonical calibrate SHA-256: \`a9f79617711614e8199ee43e48f3f74e4ef16fb6fc9379f3a62f6c41a14b90e4\`

## Candidate real-diet shot mix

\`|Δ| ≤ 2·tol\` is evaluated per six-zone row by the printed Engine/Target/Tol values.

\`\`\`text
${slice(candidate, 'ENFORCED — shooting profile', 'INFORMATIONAL — alternate pool')}
\`\`\`

## Candidate emitted play types and assisted rates

\`\`\`text
${slice(candidate, 'Play-type distribution', 'Other PBP-derived references')}
\`\`\`

## Pass provenance

\`\`\`text
${slice(diagnosis, 'Pass-count distribution', 'Terminal play-type split')}
\`\`\`

## Locked diet restoration

| Play type | Legacy shaded | Candidate real |
| --- | --- | --- |
| cut | rim .650; short mid .350 | rim .800; short mid .200 |
| spot_up | rim .070; short .090; long .050; corner .340; above .350; deep .100 | rim .130; short .084; long .050; corner .317; above .326; deep .093 |

Spot-up redistribution: each shaded donor weight × \`(.880 − .060) / .880\`, rounded to three decimals. Cut and spot-up rim values are documented-range midpoints.
`;

if (check) {
  if (readFileSync(OUT, 'utf8') !== report) throw new Error('--check FAILED: S2c2 report differs');
  console.log('--check OK: docs/S2C2_ASSIST_AND_DIET_REPORT.md byte-identical.');
} else {
  writeFileSync(OUT, report);
  console.log(`Wrote ${OUT}`);
}
